#!/usr/bin/env python3
"""Generates ../assets.h for the Nova Arcade launcher (logo + small icons)."""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "games", "NovaLance", "tools"))
import make_assets as base
from make_assets import canvas, outline, PAL, WHITE, YELLOW, ORANGE, RED, MAG, PURD, REDD, CYAN, ICE, TEAL, STD, STL, STLL

base.FONT5.update({
    "R": ["11110", "10001", "10001", "11110", "10100", "10010", "10001"],
    "D": ["11110", "10001", "10001", "10001", "10001", "10001", "11110"],
})

def logo2(text, s):
    im = base.logo(text, s)
    # recolour the gradient to cyan -> magenta for the launcher
    px = im.load()
    remap = {YELLOW: ICE, ORANGE: CYAN, RED: MAG, REDD: PURD}
    for y in range(im.size[1]):
        for x in range(im.size[0]):
            if px[x, y] in remap:
                px[x, y] = remap[px[x, y]]
    return im

def pad_icon():
    im, d = canvas(16, 10)
    d.rounded_rectangle([(0, 1), (15, 9)], radius=3, fill=STL)
    d.line([(3, 3), (3, 7)], fill=STD); d.line([(1, 5), (5, 5)], fill=STD)
    d.point((11, 4), fill=RED); d.point((13, 6), fill=CYAN)
    return outline(im)

def sd_icon():
    im, d = canvas(10, 12)
    d.polygon([(0, 0), (7, 0), (9, 2), (9, 11), (0, 11)], fill=STD)
    for x in (2, 4, 6):
        d.line([(x, 1), (x, 3)], fill=YELLOW)
    return outline(im)

SPRITES = [("logo", logo2("NOVA ARCADE", 3)), ("padicon", pad_icon()), ("sdicon", sd_icon())]

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    base.SPRITES[:] = SPRITES
    out = ["// AUTO-GENERATED by tools/make_assets.py", "#pragma once", "#include <stdint.h>",
           "#ifndef ARCADE_SPRITE_T", "#define ARCADE_SPRITE_T",
           "struct Sprite { uint16_t w, h; const uint8_t* px; };", "#endif",
           "#define PAL_SIZE %d" % len(PAL),
           "static const uint16_t PAL565[PAL_SIZE] = {" + ", ".join("0x%04X" % base.rgb565(*c) for c in PAL) + "};"]
    for name, im in SPRITES:
        w, h = im.size
        data = list(im.getdata())
        out.append("static const uint8_t %s_px[%d] = {%s};" % (name, w * h, ",".join(map(str, data))))
        out.append("static const Sprite SPR_%s = { %d, %d, %s_px };" % (name.upper(), w, h, name))
    open(os.path.join(here, "..", "assets.h"), "w").write("\n".join(out) + "\n")
    print("wrote launcher assets.h")

if __name__ == "__main__":
    main()
