#!/usr/bin/env python3
"""Original sprites for Alien Tide -> games/AlienTide/art.h (+ art_preview.png)."""
import os, sys
here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(here, "..", "..", "games", "NovaLance", "tools"))
import make_assets as base
from make_assets import canvas, outline, PAL
from make_assets import (OUT, NAVY, INDIGO, TEAL, CYAN, ICE, WHITE, STD, STL, STLL, REDD, RED, ORANGE,
                         YELLOW, MAG, PINK, GRND, GRN, LIME, PURD, PUR)
from PIL import Image

def orb(f):          # top row: floating eye-orb with trailing fins
    im, d = canvas(16, 12)
    d.ellipse([(3, 0), (12, 8)], fill=MAG)
    d.ellipse([(4, 1), (11, 6)], fill=PINK)
    d.ellipse([(6, 2), (9, 5)], fill=WHITE)
    d.rectangle([(7, 3), (8, 4)], fill=PURD)
    if f == 0:
        d.line([(3, 8), (1, 11)], fill=MAG); d.line([(12, 8), (14, 11)], fill=MAG); d.line([(7, 9), (7, 11)], fill=MAG)
    else:
        d.line([(4, 8), (4, 11)], fill=MAG); d.line([(11, 8), (11, 11)], fill=MAG); d.line([(8, 9), (8, 11)], fill=MAG)
    return outline(im)

def mantis(f):       # middle rows: angular insect with pincers
    im, d = canvas(16, 12)
    d.polygon([(4, 2), (11, 2), (13, 7), (2, 7)], fill=CYAN)
    d.polygon([(5, 3), (10, 3), (11, 6), (4, 6)], fill=ICE)
    d.point((6, 4), fill=RED); d.point((9, 4), fill=RED)
    d.line([(5, 2), (3, 0)], fill=CYAN); d.line([(10, 2), (12, 0)], fill=CYAN)
    if f == 0:
        d.line([(2, 7), (0, 10)], fill=TEAL); d.line([(13, 7), (15, 10)], fill=TEAL)
        d.line([(5, 8), (4, 11)], fill=TEAL); d.line([(10, 8), (11, 11)], fill=TEAL)
    else:
        d.line([(2, 7), (1, 4)], fill=TEAL); d.line([(13, 7), (14, 4)], fill=TEAL)
        d.line([(6, 8), (6, 11)], fill=TEAL); d.line([(9, 8), (9, 11)], fill=TEAL)
    return outline(im)

def jelly(f):        # bottom rows: bell jellyfish
    im, d = canvas(16, 12)
    d.pieslice([(1, 0), (14, 12)], 180, 360, fill=GRN)
    d.pieslice([(3, 1), (12, 10)], 180, 360, fill=LIME)
    d.rectangle([(1, 6), (14, 7)], fill=GRND)
    d.point((5, 3), fill=OUT); d.point((10, 3), fill=OUT)
    for i, x in enumerate(range(2, 14, 3)):
        off = (i + f) % 2
        d.line([(x, 8), (x + off, 11)], fill=GRN)
    return outline(im)

def pop():
    im, d = canvas(16, 12)
    for (x0, y0, x1, y1) in [(8, 6, 1, 1), (8, 6, 15, 1), (8, 6, 1, 11), (8, 6, 15, 11), (8, 6, 8, 0), (8, 6, 8, 11), (8, 6, 0, 6), (8, 6, 15, 6)]:
        d.line([(x0, y0), (x1, y1)], fill=YELLOW)
    d.ellipse([(5, 3), (10, 8)], fill=WHITE)
    return im

def cannon():
    im, d = canvas(19, 11)
    d.polygon([(0, 10), (2, 6), (16, 6), (18, 10)], fill=STL)
    d.line([(2, 6), (16, 6)], fill=STLL)
    d.rectangle([(6, 3), (12, 6)], fill=STL)
    d.rectangle([(8, 0), (10, 3)], fill=STLL)
    d.rectangle([(7, 4), (11, 5)], fill=CYAN)
    d.line([(3, 9), (15, 9)], fill=STD)
    d.point((4, 8), fill=ORANGE); d.point((14, 8), fill=ORANGE)
    return outline(im)

def saucer(f):
    im, d = canvas(28, 12)
    d.ellipse([(9, 0), (18, 7)], fill=ICE)
    d.ellipse([(11, 1), (15, 4)], fill=WHITE)
    d.ellipse([(0, 4), (27, 10)], fill=RED)
    d.ellipse([(2, 5), (25, 8)], fill=ORANGE)
    for i, x in enumerate(range(4, 25, 5)):
        d.point((x, 7), fill=YELLOW if (i + f) % 2 else WHITE)
    return outline(im)

def zig(f):
    im, d = canvas(5, 8)
    pts = [(1, 0), (3, 2), (1, 4), (3, 6), (2, 7)] if f == 0 else [(3, 0), (1, 2), (3, 4), (1, 6), (2, 7)]
    d.line(pts, fill=YELLOW); d.point(pts[-1], fill=WHITE)
    return im

def bolt():
    im, d = canvas(3, 8)
    d.line([(1, 0), (1, 7)], fill=PINK); d.point((1, 7), fill=WHITE); d.point((0, 6), fill=MAG); d.point((2, 6), fill=MAG)
    return im

SPR = [("orb0", orb(0)), ("orb1", orb(1)), ("mantis0", mantis(0)), ("mantis1", mantis(1)),
       ("jelly0", jelly(0)), ("jelly1", jelly(1)), ("pop", pop()), ("cannon", cannon()),
       ("saucer0", saucer(0)), ("saucer1", saucer(1)), ("zig0", zig(0)), ("zig1", zig(1)), ("bolt", bolt())]

out = ["// AUTO-GENERATED by tools/art/alientide_art.py", "#pragma once", "#include <stdint.h>",
       "#ifndef ARCADE_SPRITE_T", "#define ARCADE_SPRITE_T", "struct Sprite { uint16_t w, h; const uint8_t* px; };", "#endif"]
for name, im in SPR:
    w, h = im.size
    out.append("static const uint8_t %s_px[%d] = {%s};" % (name, w * h, ",".join(map(str, im.getdata()))))
    out.append("static const Sprite SPR_%s = { %d, %d, %s_px };" % (name.upper(), w, h, name))
dst = os.path.join(here, "..", "..", "games", "AlienTide")
open(os.path.join(dst, "art.h"), "w").write("\n".join(out) + "\n")
# preview
z = 6; x = 4
sheet = Image.new("RGB", (sum(im.size[0] * z + 8 for _, im in SPR) + 8, 12 * z + 10), (30, 30, 50))
for _, im in SPR:
    rgba = im.convert("RGBA"); p = rgba.load(); s = im.load()
    for yy in range(im.size[1]):
        for xx in range(im.size[0]):
            if s[xx, yy] == 0: p[xx, yy] = (0, 0, 0, 0)
    big = rgba.resize((im.size[0] * z, im.size[1] * z), Image.NEAREST)
    sheet.paste(big, (x, 4), big); x += im.size[0] * z + 8
sheet.save("/tmp/claude-0/-home-claude/1a38faee-e077-5eb1-a9c3-f629a4279cdb/scratchpad/at_art.png")
print("ok")
