#!/usr/bin/env python3
"""Generates logo assets (assets_logo.h) for the Nova Arcade games.
   python3 tools/art/logos.py   (run from the repo root)"""
import os, sys
here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(here, "..", "..", "games", "NovaLance", "tools"))
import make_assets as base
from make_assets import PAL, YELLOW, ORANGE, RED, MAG, PURD, REDD, CYAN, ICE, TEAL, GRN, GRND, LIME, WHITE, PUR

base.FONT5.update({
    "B": ["11110", "10001", "10001", "11110", "10001", "10001", "11110"],
    "K": ["10001", "10010", "10100", "11000", "10100", "10010", "10001"],
    "F": ["11111", "10000", "10000", "11110", "10000", "10000", "10000"],
    "R": ["11110", "10001", "10001", "11110", "10100", "10010", "10001"],
    "I": ["11111", "00100", "00100", "00100", "00100", "00100", "11111"],
    "S": ["01111", "10000", "10000", "01110", "00001", "00001", "11110"],
    "T": ["11111", "00100", "00100", "00100", "00100", "00100", "00100"],
    "M": ["10001", "11011", "10101", "10101", "10001", "10001", "10001"],
    "D": ["11110", "10001", "10001", "10001", "10001", "10001", "11110"],
})

def recolour(im, remap):
    px = im.load()
    for y in range(im.size[1]):
        for x in range(im.size[0]):
            if px[x, y] in remap:
                px[x, y] = remap[px[x, y]]
    return im

def write(path, name, im):
    w, h = im.size
    data = list(im.getdata())
    lines = ["// AUTO-GENERATED by tools/art/logos.py", "#pragma once", "#include <stdint.h>",
             "#ifndef ARCADE_SPRITE_T", "#define ARCADE_SPRITE_T",
             "struct Sprite { uint16_t w, h; const uint8_t* px; };", "#endif",
             "#ifndef LOGO_PAL_DEFINED", "#define LOGO_PAL_DEFINED",
             "static const uint16_t LOGO_PAL565[%d] = {%s};" % (len(PAL), ", ".join("0x%04X" % base.rgb565(*c) for c in PAL)),
             "#endif",
             "static const uint8_t %s_px[%d] = {%s};" % (name, w * h, ",".join(map(str, data))),
             "static const Sprite SPR_%s = { %d, %d, %s_px };" % (name.upper(), w, h, name)]
    open(path, "w").write("\n".join(lines) + "\n")
    print("wrote", path, w, h)

root = os.path.join(here, "..", "..", "games")
write(os.path.join(root, "Blockfall", "logo.h"), "logo",
      recolour(base.logo("BLOCKFALL", 4), {YELLOW: ICE, ORANGE: CYAN, RED: TEAL, REDD: PURD, MAG: PUR}))
write(os.path.join(root, "BrickStorm", "logo.h"), "logo",
      recolour(base.logo("BRICK STORM", 3), {YELLOW: YELLOW, ORANGE: ORANGE, RED: RED}))
write(os.path.join(root, "AlienTide", "logo.h"), "logo",
      recolour(base.logo("ALIEN TIDE", 4), {YELLOW: LIME, ORANGE: GRN, RED: GRND, REDD: PURD, MAG: TEAL}))
